name_max_length: 50
email_max_length: 255
pass_min_length: 6
size: 80
remember_1: 1
remember_0: 0
content_max: 140
picture_size: 5
user:
  size: 50
  exprire: 2
  per_page: 20
  size_2: 30
image:
  accept: "image/jpeg,image/gif,image/png"
